export const guestData = [
    {
      tableNumber: 1,
      textNumber: 'ONE',
      guests: [
        { name: "Virgilio Ranay" },
        { name: "Zarina Ranay" },
        { name: "Sarah Ranay" },
        { name: "Mark Monsanto" },
        { name: "Elvira Palalay" },
        { name: "Olivia Ranay" },
        { name: "Adiyya Ranay" },
        { name: "Arvin Ranay" },
        { name: "Ruth Ranay" },
        { name: "Ephraim Ranay" },
        { name: "Clarissa Ranay" },
        { name: "Alessa Ranay" },
        { name: "Thalia Ranay" },
      ],
    },
    {
      tableNumber: 2,
      textNumber: 'TWO',
      guests: [
        { name: "Aaron Phuong" },
        { name: "Borja Lorenzo" },
        { name: "Fatemeh Hajiloo" },
        { name: "Ferran Xarnach" },
        { name: "Hedieh Vahabi" },
        { name: "Linh Vu" },
        { name: "Mehdi Soltanzadeh" },
        { name: "Minh Vu" },
        { name: "Mohan JS" },
        { name: "Pia Nair" },
      ],
    },
    {
      tableNumber: 3,
      textNumber: 'THREE',
      guests: [
        { name: "Hector Simizu" },
        { name: "Luisa Kurata" },
        { name: "Juan Morozumi" },
        { name: "Melina Morozumi" },
        { name: "Kenzo Simizu" },
        { name: "Sofia Simizu" },
        { name: "Guillermo Ogasawara" },
        { name: "Jonatan Jardi" },
        { name: "Olivia Jardi" },
        { name: "Saori Simizu" },
      ],
    },
    {
      tableNumber: 4,
      textNumber: 'FOUR',
      guests: [
        { name: "Aida Gholami" },
        { name: "Atiyeh Zarifi" },
        { name: "Carolina Souza" },
        { name: "Deevesh Lalapure" },
        { name: "Dheyaa Ali Hussein" },
        { name: "Faranak Jalili" },
        { name: "Gerson Brito" },
        { name: "Handry Lukito" },
        { name: "Ignacio Otero" },
        { name: "Margarita Giarratano" },
      ],
    },
  ];
  